[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Validot.Tests.Unit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DynamicProxyGenAssembly2")]

[assembly: System.Reflection.AssemblyVersion("0.0.0.0")] // this line is autogenerated by the build script
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")] // this line is autogenerated by the build script
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.0")] // this line is autogenerated by the build script
[assembly: System.Reflection.AssemblyProduct("Validot")]
[assembly: System.Reflection.AssemblyCopyright("Bartosz Lenar")]
